export const arcNames = [
    "Romance Dawn",
    "Orange Town",
    "Syrup Village",
    "Baratie",
    "Arlong Park",
    "Loguetown",
    "Reverse Mountain",
    "Whiskey Peak",
    "Little Garden",
    "Drum Island",
    "Alabasta",
    "Jaya",
    "Skypiea",
    "Long Ring Long Land",
    "Water 7",
    "Enies Lobby",
    "Post-Enies Lobby",
    "Thriller Bark",
    "Sabaody Archipelago",
    "Amazon Lily",
    "Impel Down",
    "Marineford",
    "Post-War",
    "Return to Sabaody",
    "Fishman Island",
    "Punk Hazard",
    "Dressrosa",
    "Zou",
    "Whole Cake Island",
    "Reverie",
    "Wano",
    "Egghead",
  ];
  